name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: configure
        run: ./configure

      - name: Build Proxychains
        run: make

      - name: Run Proxychains
        run: ./proxychains4 -v

      - name: Run tests
        run: |
          export LD_LIBRARY_PATH=`pwd`/src
          ./src/proxychains -f dist/proxychains.conf on

      # - name: Run tests
      #   run: ./src/proxychains -f dist/proxychains.conf curl -o /dev/null -v https://sme.sk

      # - name: Run tests
      #   run: ./src/proxychains -f dist/proxychains.conf ping -c 1 sme.sk

      - uses: actions/upload-artifact@v3
        with:
          name: proxychains
          path: |
            src/proxychains
            src/libproxychains.o
            dist/proxychains.conf

#  build-macos:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: configure
#        run: ./configure
#
#      - name: Build Proxychains
#        run: make
#
#      - name: Run Proxychains
#        run: ./proxychains4 -v
#
#      - name: Run tests
#        run: ./src/proxychains -f dist/proxychains.conf on
#
#      # - name: Run tests
#      #   run: ./src/proxychains -f dist/proxychains.conf curl -o /dev/null -v https://sme.sk
#
#      # - name: Run tests
#      #   run: ./src/proxychains -f dist/proxychains.conf ping -t 1 sme.sk
